### ISSUE TITLE
Application bundle created on Big Sur will not run on older OS

### ISSUE THREAD

**Issue by cainesi** [marcelotduarte/cx_Freeze#1103]
**Describe the bug**
App frozen on OSX Big Sur will not run on earlier versions of OSX, because the minimum os of the Console bootstrap is set to 11.  (I am only recording this issue so there is something for other people to find if they are encountering the same problem.  I have a fix that would fix this if it is a common issue--see https://github.com/cainesi/cx_Freeze/tree/osx_min_version_fix)

**To Reproduce**
Build cx_Freeze on Big Sur and use it to freeze a program.  Copy the program to a computer running Catalina (or older) and try to run in.

**Expected behaviour**
Ideally, the program would just run.  There does not seem to be any real reason for the Console bootstrap to require the latest OSX.

**Desktop (please complete the following information):**
 MacOS 11 (Big Sur) on intel

**Comment by DiddiLeija** [comment]
Hi everyone, 

**I would like to test this issue**. I will use a macOS Big Sur 11.4 to freeze, and then I will try to run it under Catalina, or an older macOS. **If something happens, I'll tell you as soon as possible**.

_Note:_ @cainesi, about the branch you've mentioned... you must update it (it is 1 commit ahead, 4 commits behind `marcelotduarte:main`). Since you have enabled edits by anyone, I can update it for you. If not, please try to do it by yourself. Just tell me.

**Comment by marcelotduarte** [comment]
@cainesi It it with any version of python? 
In conda, cx-freeze does not compile in py3.9.1+ (https://github.com/conda-forge/cx_freeze-feedstock/pull/40)
It compiles in python 3.9.0, and after some changes in python 3.9.1 to support macOS 11 it is broken.
But python 36 to 38 compiles.
I tested using MACOSX_DEPLOYMENT_TARGET but it fails.
Without the env var, there are 20 errors.
With the env set to 10.13 the errors are 4 (in the current test in the link above are more errors because I tested another approach)

But basically, I mean, it is only the 3.9 version? 

And I think you could adjust the values using the sysconfig.get_config_var("MACOSX_DEPLOYMENT_TARGET")  because the value of MACOSX_DEPLOYMENT_TARGET reflects the minimal version on which binaries will run.

https://docs.python.org/3/distutils/apiref.html?highlight=macosx_deployment_target#distutils.util.get_platform

**Comment by DiddiLeija** [comment]
> But basically, I mean, it is only the 3.9 version?

I think it is.

I tried to freeze a simple script using Python **3.8.5** and Big Sur, then passed it to an older macOS, and nothing happened! So, I consider it is a Python 3.9 issue.

**Comment by cainesi** [comment]
I encountered the problem with Python 3.8.10.  

From what I can tell, the key issue is what the LC_BUILD_VERSION command in the Console bootstrap executable specifies as the "minos" parameter.  Console is built as an extension by the setup.py script, so I think would inherit a bunch of stuff from how python was built.  I am not sure if this is just a question of which version of python is used, or also of how the version was built.  

When the OS is too low (below the specified minos), the app won't run and OSX will graphically display that the bundle is un-runnable:
<img width="69" alt="Screen Shot 2021-06-15 at 3 27 18 PM" src="https://user-images.githubusercontent.com/20602705/122111991-595b5380-cdee-11eb-996a-0cd969fa5e3b.png">


> And I think you could adjust the values using the sysconfig.get_config_var("MACOSX_DEPLOYMENT_TARGET")

Yes, apparently the -mmacosx-version-min= flag is equivalent to setting the MACOSX_DEPLOYMENT_TARGET environment variable (according to google--I'm not an expert on this!).

@DiddiLeija -- I don't think setup.py is changing much.  If/when we decide to make a change we can earlier rebase the commit at that point.

**Comment by DiddiLeija** [comment]
> @DiddiLeija -- I don't think setup.py is changing much. If/when we decide to make a change we can earlier rebase the commit at that point.

Ok. I just had the concern, but don't worry.

**Comment by TechnicalPirate** [comment]
I'm also looking at a similar issue with backwards compatibility. ( Regardless of Python 3.8 or 3.9 )

Products built on Catalina won't work on Mojave, products built on BigSur won't work on Catalina / Mojave - But I'm also having to tackle getting things past Apples gatekeeper / notarization. 

Will update here as I make progress :)

**Comment by marcelotduarte** [comment]
In conda-forge we solved this issue for cx_Freeze 6.7 in py39 using a patched version of cx_Freeze  and the following variables:
```
MACOSX_DEPLOYMENT_TARGET:
- '10.9'
MACOSX_SDK_VERSION:
- '11.0'
```
For previous versions the MACOSX_SDK_VERSION is not necessary.
The cx_Freeze 6.8b1 has the patch used for conda and systems using to.

I think we need to use the same approach. In conda MACOSX_SDK_VERSION is used with xcode-select and sysroot
Maybe you that have ways to test and debug, can check how to do this. This is the log of the success build:
https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/351220/logs/77

**Comment by TechnicalPirate** [comment]
Managed to get our BigSur built images installing on Mojave without having to set those envs, seems we were getting pollution from something in our jenkins images - recreating them seemed to have fixed it 🤷‍♂️

**Comment by marcelotduarte** [comment]
@TechnicalPirate What version are you using? cx_Freeze 6.7 or 6.8b1?

**Comment by TechnicalPirate** [comment]
At this exact moment 6.7, but i'll trigger another 6.8b1 build now - should take 10minutes :)

**Comment by TechnicalPirate** [comment]
Worryingly today when i was merging down all my changes and retesting  afterwards - this issue has re-manifested for me - even reverting back to the exact commit that worked before and rebuilding is failing. Diffing jenkins logs i see nothing clear. 

It's always targeting `10.6` now 🤯 - I'll try and talk to a B&C engineer on Monday....

**Comment by TechnicalPirate** [comment]
So after further investigation it appears that cx_freeze picks the build target based on the sysconfiguration [used by the active python interpreter ](https://github.com/marcelotduarte/cx_Freeze/blob/ac25c4f862cb89f1539eddc84762429b1f501c6d/cx_Freeze/executable.py#L79) in our case we use `pyenv` to allow our pipelines to to pick python version based on the projects `pipfile`'s. _( which means we can randomly get a Python 3.9 build on bigsur one day and Python 3.9 on Mojave the next )_ 

As this looks like an issue that can't be controlled by cx_Freeze directly ( ? ) - we'll prob look at setting up a `pyenv` mirror with "trusted" versions of Python that match our minimum platform requirement. 

Will keep issue open incase someone has suggestions on how this can be addressed on cx_Freezes level ( or closed by maintainer if its not possible! ) :)

**Comment by marcelotduarte** [comment]
> which means we can randomly get a Python 3.9 build on bigsur one day and Python 3.9 on Mojave the next

This is possible when a pyenv installed python hasn't --enable-shared (see #701). Is your case?
To check:
```
import sysconfig
sysconfig.get_config_var('Py_ENABLE_SHARED')
```

**Comment by TechnicalPirate** [comment]
Hey Marcel! - So that wasn't actually the issue but it led to us asking some questions that led to the answer.

It appears your point in the other discussion re: `MACOSX_DEPLOYMENT_TARGET` was actually the correct solution.

The thing we were missing was that the jenkins images get recreated every 24 hours - so that param would be respected *initially* but then the cached python would be re-used on subsequent builds that gave the appearance of the env being ignored.

We've now got this working nicely and added a small stage to our pipeline to assert the platform specifier matches the requested target

For anyone else encountering something like this in future.

1) cx_Freeze will pickup the platform specifier of the version of Python its executing with.
2) If you're in a CI environment - using something like `pyenv` it will fetch a source distribution of python and build it respecting the OSX env vars `MACOSX_DEPLOYMENT_TARGET` and `MACOSX_SDK_VERSION`
3) Your jenkins image may then cache this distribution - so if you change target you should deleting any prior agents to force a rebuild from source respecting your env vars 

Thanks again! :)

**Comment by ghost** [comment]
Builds of software (any, not just cx_freeze) on Mac OS won't be compatible with versions older than three version you build the software on. 
Build on the oldest version of Mac OS you want to support.

**Comment by marcelotduarte** [comment]
Using wheels to run on older versions will allow an app made on a newer version to run on the previous version.
That is, on macOS 11, using wheel made for macOS 10.9 we will get it to work for all versions above.

```
pip uninstall -y cx_Freeze
pip install --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze --pre --no-cache
```

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.11](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.11.0) has just been released.
pip install --upgrade cx_Freeze
Assuming this has been resolved.
If you had issues please open a new issue.
