### ISSUE TITLE
cx_Freeze Console with PYTHONHASHSEED=0 environment variable

### ISSUE THREAD

**Issue by nisanb** [marcelotduarte/cx_Freeze#1107]
I'm trying to inject PYTHONHASHSEED environment variable which should be set to 0 when running my program.
I keep failing if I check PYTHONHASHSEED env var during runtime.

Is there an entry point I can set it to 0 before execution of my flow?

Also mentioning that this environment variable **cannot** be set at runtime.
https://stackoverflow.com/questions/30585108/disable-hash-randomization-from-within-python-program

**Comment by marcelotduarte** [comment]
It is not a bug, because cx-freeze is basically an isolated python[1].
You can create an init script[2], that set this variable internally without changes in your codebase.
Or maybe inject it using ctypes using Py_HashRandomizationFlag[3].

[1] https://docs.python.org/3/c-api/init.html?highlight=isolated#c.Py_IsolatedFlag
[2] https://github.com/marcelotduarte/cx_Freeze/tree/main/cx_Freeze/initscripts
[3] https://docs.python.org/3/c-api/init.html?highlight=isolated#c.Py_HashRandomizationFlag

**Comment by marcelotduarte** [comment]
If you build cx_Freeze from source*, using a C compiler, you can change https://github.com/marcelotduarte/cx_Freeze/blob/main/source/bases/common.c#L166
And add Py_HashRandomizationFlag
* https://cx-freeze.readthedocs.io/en/latest/development/index.html#setup
