### ISSUE TITLE
Native namespace packages cannot be freezed into library.zip

### ISSUE THREAD

**Issue by IvanKosik** [marcelotduarte/cx_Freeze#1377]
**Describe the bug**
Native namespace packages [PEP 420](https://www.python.org/dev/peps/pep-0420/) cannot be freezed into library.zip using _zip_include_packages_ option. This issue is connected with #1276. When issue #1276 was successfully fixed, now native namespace packages correctly will be placed in the file system, not in the zip file by default. But if we use _zip_include_packages_ option to place such native namespace package into zip file, nothing happens: the package will not be placed in the library.zip.

**To Reproduce**
Prepare python environment: install e.g. ruamel.yaml (version 0.17.16) or other native namespace package (parent folder of such package does not contain __init__.py file).
Then create such script to freeze into *.exe:
```
import sys
from pathlib import Path
from cx_Freeze import setup, Executable

FILE_DIR = Path(__file__).parent
BUILD_DIR = FILE_DIR / 'build'

build_exe_options = {
    'build_exe': BUILD_DIR,
    'zip_include_packages': [
        'ruamel.yaml'
    ]
}

app_base = 'Win32GUI' if sys.platform == 'win32' else None
setup(
    name='cx_Freeze Tester',
    options={
        'build_exe': build_exe_options,
    },
    executables=[Executable(
        FILE_DIR / 'main.py',
        base=app_base,
    )]
)
```

Our namespace package will not be freezed (there is no such package in the file system (lib folder), and there is no such package in the library.zip).

**Expected behavior**
Our namespace package have to be here:
build\lib\library.zip\ruamel
Because we set the _--zip-include-packages_ option for this package.

**Desktop:**
 - Platform information: Windows 10
 - OS architecture: amd64
 - cx_Freeze version: 6.10
 - Python version: 3.9.6

**Comment by marcelotduarte** [comment]
Set 'zip_include_packages': ['ruamel' ] and see what happens.

**Comment by IvanKosik** [comment]
> Set 'zip_include_packages': ['ruamel' ] and see what happens.

Unfortunately, the behavior remains the same: the package is not freezed.

**Comment by marcelotduarte** [comment]
I used the [simple](https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/simple) sample and added an `import ruamel.yaml` to it.
It build and runs with:
`python setup.py build_exe --excludes=tkinter --silent`
Then I used:
`python setup.py build_exe --excludes=tkinter --silent --zip-include-packages=ruamel`
And it works too, including ruamel to library.zip

Why I used ruamel (as I suggest before) and not full name? Because zip_include_packages include packages to zip, and packages are different from modules. See [Faq](https://cx-freeze.readthedocs.io/en/latest/faq.html#specifying-modules-and-packages).

I tested with cx_Freeze 6.10 and cx_Freeze 6.13

**Comment by marcelotduarte** [comment]
You can test the patch in the latest development build:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
