### ISSUE TITLE
sys.getwindowsversion() returns wrong info after freezing

### ISSUE THREAD

**Issue by Berserker66** [marcelotduarte/cx_Freeze#2095]
**Describe the bug**
sys.getwindowsversion() returns 6.2 after freezing, even on newer systems.

**To Reproduce**
print sys.getwindowsversion() to log

**Expected behavior**
In my case, I expected 10 to be printed

**Screenshots**

**Desktop (please complete the following information):**
Tested on Python 3.10, Windows 10

**Additional context**
According to https://learn.microsoft.com/en-us/windows/win32/sysinfo/targeting-your-application-at-windows-8-1 this is expected behaviour when the manifest does not list newer Windows versions as compatible. Which is likely the reason and would need an update of the cx-freeze manifest if I'm understanding the situation right.

**Comment by marcelotduarte** [comment]
We use the same manifest of python, but the usage in incorrect due to a setuptools option (in msys2 python it is working).
There are other bugs too.
To work correctly, a version is needed (in setup() use version keyword).

You can test the patch in the latest development build:
`pip install --force --no-cache --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
For conda-forge the command is:
`conda install -y --no-channel-priority -S -c https://marcelotduarte.github.io/packages/conda cx_Freeze`

**Comment by marcelotduarte** [comment]
[Release 6.15.10](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.10) is out!
