### ISSUE TITLE
Does cx_Freeze change DLL search path of a child process (launched with subprocess)?

### ISSUE THREAD

**Issue by igortg** [marcelotduarte/cx_Freeze#2140]
My team is migrating from Python 3.6 to 3.10 and we are having issues launching a third party application from our Python code when in frozen mode on Windows.

So we isolated the problem in a very simple script that does:
```python
subprocess.Popen(['external_app.exe'])
```
Env | Result
---- | ---- 
 Python 3.6 + cx_Freeze 5.0.2 | Works
 Python 3.10 + no freeze| Works
 Python 3.10 + cx_Freeze 6.13.1 | `external_app` starts, but fails to load one DLL from its plugin folder.

`external_app` is a C++/Qt app. The DLL that fails to be loaded is a C++ code. We did ensure that `external_app` is using the same `PATH` on both non-frozen and frozen modes. We remove the `/lib` folder created by **cx_Freeze** from `PATH` before launching the external app to avoid any clash with our own dependencies.

We also thought that it could be something missing from `os.add_dll_directory`, but I believe that this only affects search path for the Python process itself (and does not change anything on child processes created with `subprocess`). And so we are running out of ideas.

Any hint on where we could investigate this further would help.

This is the **cx_Freeze** `setup.py` we are using:
```python
build_exe_options = {"packages": ["subprocess"], "excludes": ["tkinter", "asyncio", "concurrent", "ctypes", "distutils", "email",
    "html", "http", "logging", "pydoc_data", "unittest","xml"]}

setup(  name = "start_external",
    version = "1.0",
    description = "start_external",
    options = {"build_exe": build_exe_options},
    executables = [Executable("start_external.py", base = 'console')]
)
```

**Desktop:**
 - OS architecture: Windows (win32)
 - cx_Freeze version: 6.13.1 (conda-forge)
 - Python version: 3.10 (conda-forge)

**Comment by igortg** [comment]
Just found similar issue reported on PyInstaller: https://github.com/pyinstaller/pyinstaller/issues/3795

Seems related to [SetDllDirectory from Windows API](https://pretentiousname.com/setdlldirectory_inheritance/index.html). It really affects DLL search on child processes. But I couldn't if or where **cx_Freeze** uses that.

**Comment by marcelotduarte** [comment]
There are some changes to sandbox the application, for security, and in Python 3.8+ there are additional changes with os.add_dll_directory.
You can check if the app is running in frozen mode, so I suggest putting this external_app.exe in the same directory as start_external.exe and:
```
env = os.environ.copy()
if getattr(sys, "frozen", False):
        # The application is frozen
        exedir = os.path.dirname(sys.executable)
        env["PATH"] = env["PATH"] # +";" + if needed
else:
        exedir = os.curdir()
subprocess.Popen(['external_app.exe'], cwd=exedir, env=env)
```

**Comment by marcelotduarte** [comment]
We use SetDllDirectoryW [here](https://github.com/marcelotduarte/cx_Freeze/blob/main/source/bases/common.c#L58).

**Comment by marcelotduarte** [comment]
> cx_Freeze version: 6.13.1 (conda-forge)

6.13.2 has a backport of 6.14.3 that fixes issues with msvcr. But, I recommend at least 6.15.8.

**Comment by igortg** [comment]
Thanks for the promptly response Marcelo.

We can't move `external_app.exe` to the same folder because we don't own it (user install it by themselves). 

For now we're able to make it work by calling `SetDllDirectory(None)` before launching `external_app.exe`, but that will affect search if we need to import any DLL after that. We are trying to find a way to launch `external_app.exe` without it been a child of our process (no success on that till now).

One question: changing [the code that you mentioned](https://github.com/marcelotduarte/cx_Freeze/blob/main/source/bases/common.c#L58) to use `AddDllDirectory` instead `SetDllDirectory` would change anything for **cx_Freeze**? (I read that `AddDllDirectory` does not leak changes to child process).

**Comment by marcelotduarte** [comment]
> One question: changing [the code that you mentioned](https://github.com/marcelotduarte/cx_Freeze/blob/main/source/bases/common.c#L58) to use `AddDllDirectory` instead `SetDllDirectory` would change anything for **cx_Freeze**? (I read that `AddDllDirectory` does not leak changes to child process).

I think so. It was my intention at the time of implementation, but cx_Freeze ran on official Py36+ and also ran on msys2 and conda-forge.
So I found in the conda-forge community that the best solution would be to use SetDllDirectory. Today I see that there is a note[1] about your findings, but at the time I think it wasn't there.
Msys2 and conda-forge used a patch that reverted this new approach which caused some problems with AddDllDirectory[2], as it continued to use LOAD_WITH_ALTERED_SEARCH_PATH as in Python 3.7 (The implementation in Python is [here](https://github.com/python/cpython/pull/12302/files#diff-53cfc4d59c58055e49fd0354379fe7caead9f3b2868d7d1a5b2dd85232b65178L223)).

[1] "For Win32 processes that are not running a packaged or protected process, calling this function will also affect the DLL search order of the children processes started from the process that has called the function."

[2] "The AddDllDirectory function can be used to add any absolute path to the set of directories that are searched for a DLL. If [SetDefaultDllDirectories](https://learn.microsoft.com/en-us/windows/desktop/api/libloaderapi/nf-libloaderapi-setdefaultdlldirectories) is first called with LOAD_LIBRARY_SEARCH_USER_DIRS, directories specified with AddDllDirectory are added to the process DLL search path. Otherwise, directories specified with the AddDllDirectory function are used only for [LoadLibraryEx](https://learn.microsoft.com/en-us/windows/desktop/api/libloaderapi/nf-libloaderapi-loadlibraryexa) function calls that specify LOAD_LIBRARY_SEARCH_USER_DIRS."

> For now we're able to make it work by calling SetDllDirectory(None) before launching external_app.exe, but that will affect search if we need to import any DLL after that.

How about you test something like:
```
with os.add_dll_directory(path_of_exe)?
    subprocess.Popen(...)
```

The use of SetDllDirectory in the code that I mentioned does not block the posterior usage of `os.add_dll_directory`. Several packages use it, an example is pyside6.

But returning to the previous question, as soon as I have time I will try a patch and ask you to test it.

**Comment by igortg** [comment]
> How about you test something like:

```python
with os.add_dll_directory(path_of_exe)?
    subprocess.Popen(...)
```

I tried that before, Didn't work. My guess is that since this uses `AddDllDirectory` instead `SetDllDirectory`, it does not influence child process search path.

> as I have time I will try a patch and ask you to test it.

Oh, that would be great. I'll fork and change  `AddDllDirectory` instead `SetDllDirectory` to see what happens on CI.

**Comment by igortg** [comment]
See #2144

**Comment by marcelotduarte** [comment]
You can test your PR in the latest development build:
`pip install --force --no-cache --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
For conda-forge the command is:
`conda install -y --no-channel-priority -S -c https://marcelotduarte.github.io/packages/conda cx_Freeze`

**Comment by marcelotduarte** [comment]
Do you have success?
I made some tests (with a set of samples) and at least for the latest versions of Python, it works with pip and conda.

**Comment by igortg** [comment]
Sorry that I took so long to respond.
Yes, this change worked for us. Would be great if this could go into main.

**Comment by marcelotduarte** [comment]
[Release 6.15.12](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.12) is out!
