### ISSUE TITLE
Missing modules in numpy and other packages

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#232]
Originally reported by: **Eugene Prilepin (Bitbucket: [espd](https://bitbucket.org/espd), GitHub: [espd](https://github.com/espd))**

----------------------------------------

I'm trying to use new cx_Freeze version (5.x). My application uses numpy and [pyqtgraph](https://github.com/pyqtgraph/pyqtgraph) packages. Currently, cx_Freeze loses modules from numpy and pyqtgraph.

From numpy:

- `numpy.core._methods`
- `numpy.lib.format`

From pyqtgraph:

- `pyqtgraph.debug`
- `pyqtgraph.ThreadsafeTimer`

In both cases these modules are imported via relative import. For example, in numpy:
https://github.com/numpy/numpy/blob/master/numpy/core/fromnumeric.py#L15

I have added these missing modules to `includes` and it works but it is ugly...
I think there is a problem with collecting package's modules from relative imports.

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/232

**Comment by anthony-tuininga** [comment]
*Original comment by* **Harald Hanöfner (Bitbucket: [HarryH](https://bitbucket.org/HarryH), GitHub: [HarryH](https://github.com/HarryH))**:

----------------------------------------

Did you try it with cx_Freeze 5.0.1? I guess it is same problem as I described in [Issue 228](https://bitbucket.org/anthony_tuininga/cx_freeze/issues/228/cx_freeze-501-do-not-find-some-modules). I think it depends on the changes in the finder.py between V5.0.0 and V5.0.1. But I couldn't discover it.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Eugene Prilepin (Bitbucket: [espd](https://bitbucket.org/espd), GitHub: [espd](https://github.com/espd))**:

----------------------------------------

@HarryH yes I'm working with 5.0.1 version. I have just check with 5.0.0 version. Modules have not been lost but `zip_exclude_packages` does not work correctly.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Harald Hanöfner (Bitbucket: [HarryH](https://bitbucket.org/HarryH), GitHub: [HarryH](https://github.com/HarryH))**:

----------------------------------------

Yes, there was an bug with ```zip_exclude_packages``` in 5.0.0 and it was fixed in 5.0.1. I hope Anthony can find out the new bug within the ```finder.py```.

**Comment by prusse-martin** [comment]
I have been trying to freeze a python 3 project using cx_Freeze 5.0.1 and run into this "no numpy.core._methods" issue.

Apparently the relative imports sufer with:
1. Are deferred in [`ModuleFinder._EnsureFromList`](https://github.com/anthony-tuininga/cx_Freeze/blob/5.0.1/cx_Freeze/finder.py#L197);
2. Later added to the `module.globalNames` (didn't take the reference to the source code when debugging, sorry);
3. After that they are not imported in [`ModuleFinder._ImportDeferredImports`](https://github.com/anthony-tuininga/cx_Freeze/blob/5.0.1/cx_Freeze/finder.py#L289) call to [`ModuleFinder._EnsureFromList`](https://github.com/anthony-tuininga/cx_Freeze/blob/5.0.1/cx_Freeze/finder.py#L197) since they are already in the `module.globalNames`;

Just ignoring the `module.globalNames` and just checking if the module have already been imported get all relative imports. I didn't have time to run the tests and/or create a proper pull request, maybe this have some side effect I am unaware of. I am pasting the patch here now, when I get time I will open a PR for this if it still relevant.
```diff
diff --git a/cx_Freeze/finder.py b/cx_Freeze/finder.py
index d2c47be..eaaaf34 100644
--- a/cx_Freeze/finder.py
+++ b/cx_Freeze/finder.py
@@ -204,9 +204,9 @@ class ModuleFinder(object):
             deferredImports.append((caller, packageModule, fromList))
         else:
             for name in fromList:
-                if name in packageModule.globalNames:
-                    continue
                 subModuleName = "%s.%s" % (packageModule.name, name)
+                if self._modules.get(subModuleName) is not None:
+                    continue
                 self._ImportModule(subModuleName, deferredImports, caller)

     def _FindModule(self, name, path, namespace):
```

cc: @nicoddemus

**Comment by dcolascione** [comment]
@prusse-martin 's fix works for me

**Comment by anthony-tuininga** [comment]
I have replicated the issue. The fix "works", but it also includes a lot more noise in the list of modules that cx_Freeze claims don't exist. I have an idea for an improved patch which I hope to address soon.

**Comment by rexovatek** [comment]
Hi there - has there been an update regarding this fix?  I'm encountering the same issue with the asyncio module, which uses a lot of relative imports.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
