### ISSUE TITLE
Window GUI Problem

### ISSUE THREAD

**Issue by samuelcalegari** [marcelotduarte/cx_Freeze#250]
hello 
I try to build an **GUI application** on **windows** (I use a webview) but when try to execute my project nothing appends
the project works correctly when I use "python webviewpm.py"
an cx_freeze build correctly console application

I use **Python 3.6** and cx_freeze **5.0.1**

**webviewpm.py:**

import webview
webview.create_window("Yahoo!", "https://www.yahoo.fr")

**setup.py**

from cx_Freeze import setup, Executable

buildOptions = dict(packages = [], excludes = [])

import sys
base = 'Win32GUI' if sys.platform=='win32' else None

executables = [
    Executable('C:\\python\\webviewpm.py', base=base)
]

setup(name='webviewpm',
      version = '1.0',
      description = '',
      options = dict(build_exe = buildOptions),
      executables = executables)

Thanks in advance

**Comment by kierun** [comment]
I get the exact same problem with the basic [wx example](https://github.com/anthony-tuininga/cx_Freeze/tree/master/cx_Freeze/samples/wx) on Windows 10. 

My code uses logging and I tried to log into a file but nothing is written to the file. Which is fair since the file itself *is not created*.

Note that the code is build under a virtual environment created by Python -- `python -m venv …`

Some versions:
- Python 3.6.3
- cx_Freeze 5.1
- Windows 10 version 1709 (OS Build 16299.19)
- wxPython 4.0.0b2 but that should really not matter.

**Comment by kierun** [comment]
I just tried `60b1` and the problem has vanished! I get a nice⸮ GUI on screen.

@samuelcalegari  Could you try to update (`pip install cx_freeze==6.0b1`) and run your code again?

**Comment by anthony-tuininga** [comment]
You can also try the v5.x branch directly (or 5.1.1 when it gets released).

**Comment by samuelcalegari** [comment]
hello it's works fine ;)
thanks a lot
