### ISSUE TITLE
cx_Freeze 5.0.1 and PyQt - freezing copied too many files

### ISSUE THREAD

**Issue by TCRserver** [marcelotduarte/cx_Freeze#256]
I got a issue with cx_Freeze 5.0.1, PyQt5.8 and Python 3.6, cx_Freeze, copied too many files from the Qt Source directory.

With cx_Freeze 5.0 and Py3.5 I get a build Directory with ~30 MB and a few directories.
After updateting the projekt to Py3.6 and cx_Freeze 5.0.1 i get an build Directory with ~200 MB.
Including many unnecessary files, such as the complete QT Resources Directory

**Comment by mretegan** [comment]
I had the same problem with the current version of cx_Freeze. The regression was introduced following commit https://github.com/anthony-tuininga/cx_Freeze/commit/785632b701df0bb40d850f51c9bd15759019d2db, which actually predates version 5.0. With the code before that commit I got a "decent" sized build folder on Windows with Python 3.5.3 and PyQt 5.8.2.

**Comment by doudz** [comment]
This happens to me too.
The problem is cx_freeze include the whole PyQt5 package, including docs

**Comment by noragen** [comment]
cx-Freeze==5.0.2

I have to confirm: Way to much things included.
Have a look at that generated freezed folder trees attached, before and after.
Both are working, but "after.txt" contains way too much unnecessary stuff.

[after.txt](https://github.com/anthony-tuininga/cx_Freeze/files/1148270/after.txt)
[before.txt](https://github.com/anthony-tuininga/cx_Freeze/files/1148269/before.txt)

@anthony-tuininga If you need a tester for pyqt4/5, please notify me! 
My project is is made pyqt4/5 compatible. So it should be easy to compare the freeze between and also to compare with past versions. Maybe you could rework the commit @mretegan mentioned above or revert temporarily and improve it.

It looks also that the "library.zip" has been replace with python.zip. Additionally files/directories from "library.zip" has been moved to the root folder structure and has been enriched with unnecessary files/folders.

**Comment by anthony-tuininga** [comment]
@noragen, the default was changed so that the *entire* package is copied to the target folder. This was done to avoid problems with packages that assume their contents are found in their entirety on disk -- and those numbers seemed to be growing. You can use the new option zip_include_packages to revert back to the original behaviour for all or particular packages. If you have specific suggestions for the PyQT package, let me know! Thanks.

**Comment by noragen** [comment]
Hi Anthony,

 

thanky you for the reply. This is a nice hint.

 

Today I've got another problem. In Anaconda2 I wanted to freeze a program, but there was a problem, when I wanted to run the .exe.

At the end I figured out there was a QT-dependency missing ("plugins/platform"):

Because there are so many versions of python out there I wanted to have something I can use to find that folder.

Maybe you can use it to fix or workaround cx_freeze with this. I think there is even a ticket in the tracker with this issue for cx_freeze.

 

The files from the found folder just needed to be placed in dist/platform/

 

 

import os
import PyQt5

#ok, we have PyQt5

 

def ld(x):
    try:
        return os.listdir(x)
    except:
        return []

 

def find_pyqt5_platforms_folder():
    PA=["python", "anaconda"]
    subpaths =[
        ["."],                                  #Linux
        ["Lib","site-packages","PyQt5","Qt"], #Python
        ["Library"]                              #Anaconda
    ]
    subsubpath=[['plugins', 'platforms']]
    QTPATH=PyQt5.__path__[0]
    QTPATH_s=QTPATH.split(os.sep)
    part=list(filter(lambda x: any(i in x.lower() for i in PA),QTPATH_s))[0]
    pBegin=QTPATH.find(part)
    begin=QTPATH[:pBegin+len(part)]
    for sp in subpaths:
        for ssp in subsubpath:
            folder=os.sep.join([ os.sep.join([begin, os.sep.join(sp)]), os.sep.join(ssp) ])
            fl=ld(folder)
            if fl:
                for f in fl:
                    if "qminimal" in f:
                        return folder

 

Gesendet: Sonntag, 05. November 2017 um 04:18 Uhr
Von: "Anthony Tuininga" <notifications@github.com>
An: anthony-tuininga/cx_Freeze <cx_Freeze@noreply.github.com>
Cc: noragen <noragen@gmx.net>, Mention <mention@noreply.github.com>
Betreff: Re: [anthony-tuininga/cx_Freeze] cx_Freeze 5.0.1 and PyQt - freezing copied too many files (#256)


@noragen, the default was changed so that the entire package is copied to the target folder. This was done to avoid problems with packages that assume their contents are found in their entirety on disk -- and those numbers seemed to be growing. You can use the new option zip_include_packages to revert back to the original behaviour for all or particular packages. If you have specific suggestions for the PyQT package, let me know! Thanks.

**Comment by anthony-tuininga** [comment]
On Fri, Nov 10, 2017 at 9:06 AM, noragen <notifications@github.com> wrote:

>
> Hi Anthony,
>
>
>
> thanky you for the reply. This is a nice hint.
>

You're welcome.


> Today I've got another problem. In Anaconda2 I wanted to freeze a program,
> but there was a problem, when I wanted to run the .exe.
>
> At the end I figured out there was a QT-dependency missing
> ("plugins/platform"):
>
> Because there are so many versions of python out there I wanted to have
> something I can use to find that folder.
>
> Maybe you can use it to fix or workaround cx_freeze with this. I think
> there is even a ticket in the tracker with this issue for cx_freeze.
>

Can you elaborate? Perhaps give some sample code that demonstrates the
problem? I haven't done much with QT so can't help much directly!

**Comment by zdenop** [comment]
I use cx-freeze 6.0b1 (pyQt5 5.10 on windows 10 & python 3.6 64bit) and and I hoped this is issues is fixed . Unfortunatelly not.  Even for simple script:

```
import sys
from PyQt5.QtWidgets import (QApplication, QMainWindow)

class MainWindow(QMainWindow):
    """Main window class."""
    def __init__(self):
        """Initialization of Main window."""
        QMainWindow.__init__(self)

if __name__ == "__main__":
    app = QApplication(sys.argv)
    mainWin = MainWindow()
    mainWin.show()
    sys.exit(app.exec_())
       """Initialization of Main window."""
        QMainWindow.__init__(self)

if __name__ == "__main__":
    app = QApplication(sys.argv)
    mainWin = MainWindow()
    mainWin.show()
    sys.exit(app.exec_())
```
is created app (`cxfreeze simple_gui.py --target-dir dist_cx`) with 282 Mb size!. When I have a look at content of dist_cx I can see there e.g. VCRUNTIME140.dll in several places:
```
.\VCRUNTIME140.dll
.\lib\VCRUNTIME140.dll
.\platforms\VCRUNTIME140.dll
.\lib\pyQt5\VCRUNTIME140.dll
.\lib\pyQt5\Qt\bin\VCRUNTIME140.dll
.\imageformats\VCRUNTIME140.dll
```

Is it really necessary? Also other libraries are there multiple times (MSVCP140.dll, Qt5Gui.dll, Qt5Core.dll).
Is it possible to avoid this situation?

**Comment by ttphan** [comment]
I had the same problem, but with PySide2 (Python 3.6.2, 64-bit, PySide2 5.11.0a1, cx-Freeze 6.0b1, Windows 10)

I solved part of the problem by including 'zip_include_packages': 'PySide2' to the build options, but then it threw the following error when building on Windows:

`This application failed to start because it could not find or load the Qt platform plugin "windows" in "".`

This is due to the missing platforms folder from PySide2:
[https://stackoverflow.com/questions/44040630/could-not-find-or-load-the-qt-platform-plugin-windows-cx-freeze-exe-pyth](https://stackoverflow.com/questions/44040630/could-not-find-or-load-the-qt-platform-plugin-windows-cx-freeze-exe-pyth)

Copying the platforms folder to the root (or including it in the 'include_files' parameter) solved the problem for me! Cut down the size from 700-800MB to ~80MB. Not perfect, but still way better.

Additionally, my images stopped working, but that was due to the missing imageformats folder:
[https://stackoverflow.com/questions/5721953/images-not-showing-when-running-a-frozen-pyqt-app-on-another-computer?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa](https://stackoverflow.com/questions/5721953/images-not-showing-when-running-a-frozen-pyqt-app-on-another-computer?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)

Applying the same trick to the imageformats folder solved it.
Hope this helped!

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Assuming this has been resolved.
If you had issues please open a new issue.

**Comment by break11** [comment]
In my case bug steel present. cxfreeze 6.9 - tested with pyqt5 and pyside2 on ubuntu 16.04 and 18.04. It is look like cxfreeze put whole qt library in dist directory. Finally build directory size is 300-450 Mb. Using "excludes" options did not help to solve problem.

**Comment by marcelotduarte** [comment]
> cxfreeze put whole qt library in dist directory

This is the default behavior.
Using [zip_include_packages](https://cx-freeze.readthedocs.io/en/latest/setup_script.html#cmdoption-arg-zip_include_packages) for PyQt5 or PySide2 only the used shared libraries are copied.

**Comment by break11** [comment]
Thanks for the reply, by combining the "excludes" and "zip_include_packages" options I was able to achieve a size reduction, although it doesn't seem obvious.

```
options = {
    "build_exe": {
        "excludes": [
            "tkinter",
            "unittest",
            "email",
            "http",
            "xml",
            "pydoc",
            "PySide2.QtNetwork",
        ],
        "zip_include_packages": ["PySide2"],
    },
}

```

**Comment by marcelotduarte** [comment]
It is a hack ;-) Reading the code we end up discovering this possibility. For packages that have many extensions in C this works well, reducing the copying of these extensions to a minimum, but for packages with many modules in python it ends up being slow. For pyqt5, pyside2 and wxpython this is very good.

**Comment by witc** [comment]
Hi, I have python/qml/PySide6 application, after using cx_Freeze (last version) the build folder has about 590 MB. The largest folder is PySide6 (395 MB).
If some solution was add  _"zip_include_packages": ["PySide2"],_ - so then size increased to 1.1 GB. Is there any chance to dramaticly reduce a size?
Thank you very much.

**Comment by marcelotduarte** [comment]
@witc "zip_include_packages": ["PySide6"]

**Comment by witc** [comment]
> @witc "zip_include_packages": ["PySide6"]

My mistake in the comment. I used "zip_include_packages": ["PySide6"] - but as I wrote - it did not help.

**Comment by marcelotduarte** [comment]
@witc Check this sample: https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/pyside6
