### ISSUE TITLE
include_msvcr doesn't bundle vcruntime140.dll when bdist_msi is run inside a virtualenv

### ISSUE THREAD

**Issue by henryborchers** [marcelotduarte/cx_Freeze#275]
include_msvcr doesn't seem to add vcruntime140.dll to the package if it's built inside the virtualenv but has no trouble if built outside.

I'm building on a Windows Server 2012 R2
Python 3.6 64-bit.

**Comment by rcutmore** [comment]
I think this is an issue with virtualenv not copying *vcruntime140.dll* into the virtual environment. If this file is manually copied to the virtual environment then the build works fine for me.

I noticed when using venv instead of virtualenv, the corresponding virtual environment has *vcruntime140.dll* copied to it and I have no issues with the cx_Freeze build.

[Here](https://github.com/pypa/virtualenv/issues/796) is a related bug report on the virtualenv issue tracker.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
