### ISSUE TITLE
Only import what needs to be imported

### ISSUE THREAD

**Issue by tristan957** [marcelotduarte/cx_Freeze#282]
I'm writing a program making use of `pillow` (`PIL`). My import statement looks like this:
```python
from PIL import Image, ImageTk
```
Because `PIL` also has an `ImageQt` module, cx_Freeze also wants to import `PyQt5`. Now I just avoided this issue by using an exclude in my build option. Even still builds could become infinitely smaller if for instance the `PIL` folder within my `build` folder only copied exactly what I needed for my program to run i.e. `Image`, `ImageTk`, and any of the `PIL` modules those two depend on. Hope I made this clear enough. Otherwise thanks for the great program. Really does work wonders.

**Comment by anthony-tuininga** [comment]
You're welcome. And thanks for the comment. The current versions of cx_Freeze err on the side of putting too much into the distribution, as otherwise errors occur because things are missing that should be there. The solution you came up with (adding to the exclude options) is what you want to do in these cases. Someone else may *want* PyQT to be present! There may be some need for specifying a "soft" dependency at some point -- but how to do that in a way that makes sense to people I'm not sure. Further comments welcome!
