### ISSUE TITLE
Compiling a Python script on Linux into a Windows executable

### ISSUE THREAD

**Issue by w1397800** [marcelotduarte/cx_Freeze#390]
hello, i want to compiling a Python script on Linux into a Windows executable, can the cx_freeze do that?
by the way, i use pyton3.6 and centos 6.4. look forward your reply!

**Comment by MateuszDabrowski** [comment]
Hello,

Unfortunately, it is not possible directly - no freezer can do this, as they all use OS specific code.
You can use cx_Freeze on any platform to freeze your app for that specific platform (on linux pack for linux, on windows pack for windows).

You may try with either virtualization or containerization to for example launch cx_Freeze via Windows docker container, however, your Windows user may encounter warnings while launching your .exe due to Microsoft's policy regarding .exe's packed in virtual environments.

**Comment by w1397800** [comment]
thanks for your reply, i will think about another strategy to avoid this problem.
