### ISSUE TITLE
Allow storing library.zip and other depedencies alongside the main application

### ISSUE THREAD

**Issue by LeonarddeR** [marcelotduarte/cx_Freeze#413]
Library.zip and other dependencies are now stored in a lib folder. It would be great if this could be configurable, i.e. load the dependencies from the application's root directory.

I understand that this is hardcoded in the compiled base executable. May be it could be considered to add a `#ifndef CX_PATH_FORMAT` check, so people can compile their own base executable with an overriden definition while not requiring to override common.c as well.

**Comment by marcelotduarte** [comment]
For Linux PR #518

**Comment by marcelotduarte** [comment]
Since 7.1 has an option [zip_filename](https://cx-freeze.readthedocs.io/en/stable/setup_script.html#cmdoption-arg-zip_filename).
In other words, it can have library.zip or any other name, and you can also choose not to have a zip file.
I'm closing the issue as I have no plans to remove the lib directory.
