### ISSUE TITLE
5.1.1, 6.0b1: build doesn't load libpython on linux (python 3.5, 3.6)

### ISSUE THREAD

**Issue by skozlovf** [marcelotduarte/cx_Freeze#425]
Executable created with `5.1.1`, `6.0b1` and b18b4c3c fails with error:
```
Fatal Python error: Py_Initialize: Unable to get the locale encoding
Traceback (most recent call last):
  File "/home/vuser/.pyenv/versions/3.6.6/lib/python3.6/encodings/__init__.py", line 31, in <module>
zipimport.ZipImportError: can't decompress data; zlib not available
```

I used docker image with python `3.5.6`, `3.6.6` build with `pyenv`. The exe tested in various docker containers.

If run with `LD_LIBRARY_PATH` set then it runs correctly. So the issue is that the exe doesn't load `libpython3.X.so` because it searches in wrong paths (it doesn't search in the exe parent and `lib` dirs)

Some of the search paths (from `strace` log):
```
/usr/lib/x86_64-linux-gnu/tls/x86_64/libpython3.6m.so.1.0
/usr/lib/x86_64-linux-gnu/tls/libpython3.6m.so.1.0
/usr/lib/x86_64-linux-gnu/x86_64/libpython3.6m.so.1.0
/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
/lib/libpython3.6m.so.1.0
/usr/lib/libpython3.6m.so.1.0
```

At the same time it correctly loads some other libs:
```
stat("/project/build/exe.linux-x86_64-3.6/lib/library.zip", {st_mode=S_IFREG|0644, st_size=807258, ...}) = 0
open("/project/build/exe.linux-x86_64-3.6/lib/library.zip", O_RDONLY) = 3

open("/project/build/exe.linux-x86_64-3.6/lib/zlib.cpython-36m-x86_64-linux-gnu.so", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260\34\0\0\0\0\0\0"..., 832) = 832

```
Here is repo with demo scripts and `strace` logs: https://github.com/skozlovf/cxfreeze-tests.
Just run `./runtests.sh`. Take a look please.

PS probably related issues #324, #392.

**UPD1**:

I  have found what if build python and executable in Debian Jessie then it works fine. Above is built with Debian Stretch.

**Comment by Jerakin** [comment]
Also probably related to https://github.com/anthony-tuininga/cx_Freeze/issues/399 and maybe https://github.com/anthony-tuininga/cx_Freeze/issues/411

**Comment by Jerakin** [comment]
> UPD1:
>
> I have found what if build python and executable in Debian Jessie then it works fine. Above is built with Debian Stretch.

I got this error on macOS 10.13.3 but building in a virtualbox with 10.12 works fine.

**Comment by jomann09** [comment]
I'm using cx_Freeze 5.1.1 and building on SLES 11.4 which is giving the exact same issue (with Python 2.7 built from source)

When running `ldd` on the binary created by cx_Freeze I am missing the `libpython2.7.so.1.0` which is weird since it seems like the other systems I checked show it. That is the only difference that I can think of, but not sure if it is actually causing the problem. However, following the stack trace on the system with and without that link in the binary, the one with it finds the library right away and never has issues, while the one without it, when it tries to load libpython (not at the beginning like the other one) it fails to find it unless you update the `/etc/ld.so.conf` or set `LD_LIBRARY_PATH`.

Not sure if that has anything to do with it but I am getting the same `zipimport` error.

**Comment by jomann09** [comment]
So interestingly enough, on a whim I compiled python manually without `--enable-shared` and did a clean build on SLES 11 and then on a new system tried to run the program and it worked fine. Without the error from trying to load in the `libpython2.7.so.1.0`. It definitely has something to do with the shared library and how it tries to load it. Not sure what issues it'll cause to not have the shared library.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
