### ISSUE TITLE
no module named encodings

### ISSUE THREAD

**Issue by medns** [marcelotduarte/cx_Freeze#667]
Packaged program crash with "no module named encodings".
because Py_SetPath(...) must be called before Py_Initialize() in InitializePython in Common.c

**Comment by marcelotduarte** [comment]
Please, post more information about your system. I'm presuming that you're using Linux, but what?
SO system and version
Python version, native or anaconda, etc.

**Comment by medns** [comment]
macOS 10.14
Python 3.7 native

I think it just a pure cx_Freeze bug, previous version of cx_Freeze [Common.c#334286e654acf458859508c82d71a09d16e66fa1](https://github.com/anthony-tuininga/cx_Freeze/blob/334286e654acf458859508c82d71a09d16e66fa1/source/bases/Common.c)  is no problem

**Comment by marcelotduarte** [comment]
cx_Freeze 6.2 has just been released. Please, try it.

**Comment by mikedarcy** [comment]
We are also encountering this bug on MacOS 10.15.6, Python 3.5, cx_Freeze version 6.2. 

The refactored code in this commit seems to be the issue: https://github.com/marcelotduarte/cx_Freeze/commit/8762f3e803aed3ded5a4ec1733548211173b3335#diff-2c51a3c35ee65d229557cb21c1705b40 and this code is still in master and is part of 6.2 PyPi release.

It looks like @medns is correct, since `Py_SetPath` is indeed now being called after `Py_Initialize`. Seems like simply moving `Py_Initialize`  from line 159 down to line 183 should do the trick...

**Comment by marcelotduarte** [comment]
Before the patch, it is used Py_SetPath. In the patch is used another function, PySys_SetPath, that have different behavior to do the same task, but I need to check its compatibility. The main difference is that calling PySys_SetPath after Py_Initialize, paths with utf-8 or another encoding are fully functional.

**Comment by marcelotduarte** [comment]
@medns @mikedarcy 
If you use cx_Freeze 6.1 this problem disappears?
For me, in Linux, version 6.1 has issues with utf8 paths, args, etc.
In 6.2 it builds and runs from Py 3.5 to 3.8

**Comment by mikedarcy** [comment]
Using 6.1, everything works as before. Unfortunately, my frozen app requires 6.2 changes, specifically those from https://github.com/marcelotduarte/cx_Freeze/pull/608 (and now it can't work without them), so I am really stuck, since I can't realistically downgrade. 

I am building the frozen app with cx_Freeze 6.2 PyPi release code, Python 3.5.4, and MacOS 10.11.6 (which is admittedly old, but I was trying to support oldest MacOS reasonably possible) and what is notable is that the app _does_ function normally on the 10.11.6 system, but not on a 10.15.6 system, as reported by a user. 

Also of note is that the freezing is being done in a virtualenv, which has worked fine previously, but might be a factor now.

Wish I had more info for you. I'm waiting on getting my hands on a Mac with 10.15.x so I can test it directly myself and maybe help get to the bottom of this.

**Comment by robes** [comment]
I can recreate the issue on macOS 10.15.6, python 3.5.6, and (fwiw) Apple clang version 11.0.3 (clang-1103.0.32.62) with a simple hello world script.

1. Cloned the cx_Freeze repo (master), built and installed it
2. Created a simple `hello.py`
```python
import sys

def main():
    sys.stdout.write('hello world\n')
    return 0

if __name__ == '__main__':
    sys.exit(main())
```
3. Made an executable out of it with `cxfreeze hello.py --target-dir dist`
4. Gave it a try
```shell command
dist % ./hello
Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module named 'encodings'

Current thread 0x00000001126d8dc0 (most recent call first):
zsh: abort      ./hello
```

**Comment by marcelotduarte** [comment]
@robes, with py 35 has a bug, that if I remember @mikedarcy pointed me (PR #700).
It was merged. I need some more tests and I release a version.
And for metadata support has a improved version merged too (PR #697)

**Comment by marcelotduarte** [comment]
@robes @mikedarcy @medns 
If you have a C compiler, you can test the development version:
`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@develop`

**Comment by robes** [comment]
I tried the development version and froze my simple hello.py script. I get a similar though maybe not exact error when running it.

```
% ./dist/hello 
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x0000000109955dc0 (most recent call first):
zsh: abort      ./dist/hello
```

I should have mentioned that I am using conda based virtual environments when doing these tests, in case that could affect either cx freeze itself or the behavior of the frozen script.

**Comment by robes** [comment]
It worked with a non-conda environment. This is good. So I went back and disabled my conda env, created a new py 3.7 virtual env based on the macOS system installed python3, installed your (@marcelotduarte) development version, and froze my hello.py script. This time the frozen script worked.

**Comment by mikedarcy** [comment]
I just tried the dev update using our existing build system (Python 3.5.4 venv, MacOSX 10.11.6) and got this:

`error: otool returned a dependent file that could not be found: @executable_path/../.Python`

No stack trace or other info emitted.

**Comment by mikedarcy** [comment]
I was able to get around my previous reported `otool` error by starting with a fresh `venv` for freezing our app. Unfortunately, we are still having the same issue with executing any script built into the frozen application:

```
Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module named 'encodings'
```

The `encodings` module directory (and its code) _is_ in the app `lib` directory, it just cannot be found when embedded Python is initializing.  It was also getting copied to the lib directory properly before the latest changes.

**Comment by marcelotduarte** [comment]
@mikedarcy Your python is anaconda?
If you can, install cx-freeze, build and report the following tests:
#### pip install cx-freeze==6.1
#### pip install cx-freeze==6.2
#### pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@master
#### pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@develop

**Comment by mikedarcy** [comment]
I do not use Anaconda. My Python is mac distro from Python.org, 3.5.4 from [here](https://www.python.org/ftp/python/3.6.4/python-3.6.4-macosx10.6.pkg). I create a virtual environment using `python3 -m venv` , install `cx_freeze` into that venv along with my application and all of its dependencies (which are quite a few, including PyQt5), and freeze from within that virtualenv.

I have frozen the app in this venv using all of the above, and the only one that still works is `6.1`. As I stated, its not really practical for me to use 6.1 anymore due to needing improvements in the 6.2 release.

**Comment by marcelotduarte** [comment]
@mikedarcy @cainesi 
Can you test this branch?
pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@syspath

**Comment by cainesi** [comment]
That worked for me, thanks.

**Comment by marcelotduarte** [comment]
@cainesi Can you test another branch?
I discovered that encodings packages should be included in library.zip, but this didn't happen. The patch that you (and others) pointed only exposed the error, because of need encodings. But in Linux, this doesn't occurs.

pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@encodings

**Comment by cainesi** [comment]
@marcelotduarte When I freeze with this branch it did not work on its own--same error about not finding encodings.  But if I swap in the Console from your syspath branch it works. In any case, encodings is being put in the zip file instead of the file system.  Is there a particular reason we do not want encodings in the file system?  (Just general cleanliness?)

FYI, I was testing this with a version that also included pull request #590, with some additional tweaks to fix the issue I mentioned in my last comment there.

**Comment by marcelotduarte** [comment]
@cainesi 
In my previous comment "encodings packages should be included in library.zip" is a mistake. The error here is "the chicken or the egg dilemma".
I need encodings to decode the path and a path to found the encodings (encodings can be in library or in the file system).
The patches in the branch 'syspath' address this, setting the path in raw encoding, read the encodings e setting the path again.

>  Is there a particular reason we do not want encodings in the file system?
After I understood this question, no!
But it has 123 files, and we use at a few (ASCII, utf_8, Zlib and 1 locale-dependent)...

**Comment by robes** [comment]
FWIW, I was able to freeze my simple hello.py example that I described above and it worked. thanks.

**Comment by marcelotduarte** [comment]
@robes @mikedarcy cx_Freeze 6.3 has just been released.

**Comment by robes** [comment]
Excellent. Thanks!
