### ISSUE TITLE
Dependency with double dot path "../.." copied to relative dir freeze dir

### ISSUE THREAD

**Issue by louisng5** [marcelotduarte/cx_Freeze#979]
I recently updated cx_Freeze from version 5.1.1 to 6.4,

I have some .so files dependency eg :

"....../python3.7/lib-dyload/../../libz.so"

because the dependency ends with "../../libz.so"

so it is copied to 

"{FREEZE_DIR}/../../libz.so"

In version 4, the dependency is copied to :
"{FREEZE_DIR}/libz.so"

which is what I expect.

Any idea how to solve the issue?

**Comment by marcelotduarte** [comment]
Is Linux? If so, I think that the fix is on #967 and some previous commits, which solves issues with packages distributed as manylinux wheels, like Pillow and NumPy.
If you are using pip, can you test with:
1) Current pypi version:
pip install -U cx-freeze
2) Or main development branch: 
`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@main`
Please note that patchelf and the C compiler must be installed. 
To install patchelf in debian/ubuntu:
`sudo apt install patchelf`
Now you can test the development version:
`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@main`
If your project builds successfully, please notify me with a comment.

**Comment by louisng5** [comment]
Thanks @marcelotduarte 

Unfortunately my organisation wouldn't allow me to do that. But the part of the code that caused the issue is identified. I have modified the code so that it now copy to both targetDir and targetDir + relpath as a temporary fix.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Assuming this has been resolved.
If you had issues please open a new issue.
